# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 09:48
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(
                    auto_now_add=True, verbose_name='created')),
                ('modified',
                 django_extensions.db.fields.ModificationDateTimeField(
                     auto_now=True, verbose_name='modified')),
                ('location',
                 django.contrib.gis.db.models.fields.PointField(blank=True,
                                                                null=True,
                                                                srid=4326)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('adjust_30_min', models.BooleanField(default=False)),
                ('status', models.PositiveIntegerField(
                    choices=[(10, 'Opened'), (20, 'WaitingForUserDecide'),
                             (30, 'UserRejectSuggestions'), (40, 'Reserved'),
                             (50, 'TimeOut'), (60, 'Booked'),
                             (70, 'Canceled')],
                    default=10)),
                ('doctor', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='appointments',
                    to=settings.AUTH_USER_MODEL)),
                ('patient',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='self_appointments',
                                   to=settings.AUTH_USER_MODEL)),
                ('treatments',
                 models.ManyToManyField(related_name='used_in_appointments',
                                        to='clinics.Treatment')),
            ],
            options={
                'db_table': 'appointments',
            },
        ),
        migrations.CreateModel(
            name='AppointmentClinicEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(
                    choices=[(10, 'Active'), (20, 'Accepted'),
                             (30, 'Suggested'), (40, 'Rejected'),
                             (50, 'Inactive'), (60, 'RejectedSuggestions')],
                    default=10)),
                ('appointment',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='events',
                                   to='appointments.Appointment')),
                ('clinic',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='appointment_events',
                                   to='clinics.Clinic')),
            ],
            options={
                'db_table': 'appointment_actions',
            },
        ),
        migrations.CreateModel(
            name='AppointmentSuggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('adjust_30_min', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('is_chosen', models.NullBooleanField()),
                ('appointment_event',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='suggestions',
                                   to='appointments.AppointmentClinicEvent')),
                ('doctor',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='in_suggestions',
                                   to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'appointment_suggestions',
            },
        ),
    ]
