# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 09:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('appointments', '0002_appointmentschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentReminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('before', models.DurationField()),
                ('duration', models.PositiveIntegerField()),
                ('time_type', models.CharField(
                    choices=[('minutes', 'Minutes'), ('hours', 'Hours'),
                             ('days', 'Days'), ('weeks', 'Weeks')],
                    default='minutes', max_length=10)),
                ('already_send', models.BooleanField(default=False)),
                ('task_id',
                 models.CharField(blank=True, max_length=255, null=True))
            ],
            options={
                'db_table': 'appointment_reminders',
            },
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='time',
        ),
        migrations.RemoveField(
            model_name='appointmentsuggestion',
            name='date',
        ),
        migrations.RemoveField(
            model_name='appointmentsuggestion',
            name='time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointmentsuggestion',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointmentreminder',
            name='appointment',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='reminder', to='appointments.Appointment'),
        ),
    ]
