# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('appointments', '0003_auto_20170403_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('before', models.DurationField(blank=True)),
                ('duration', models.PositiveIntegerField()),
                ('time_type', models.CharField(
                    choices=[('minutes', 'Minutes'), ('hours', 'Hours'),
                             ('days', 'Days'), ('weeks', 'Weeks')],
                    default='minutes', max_length=10)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'reminder_time_types',
            },
        ),
        migrations.RemoveField(
            model_name='appointmentreminder',
            name='before',
        ),
        migrations.RemoveField(
            model_name='appointmentreminder',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='appointmentreminder',
            name='time_type',
        ),
        migrations.AddField(
            model_name='appointmentreminder',
            name='reminder_time',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='appointment_reminder',
                to='appointments.ReminderTime'),
        ),
    ]
