# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 18:53
from __future__ import unicode_literals

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_auto_20170419_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentschedule',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='appointmentschedule',
            name='start_time',
        ),
        migrations.AddField(
            model_name='appointmentschedule',
            name='duration',
            field=django.contrib.postgres.fields.ranges.DateTimeRangeField(
                null=True),
        ),
    ]
