# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20170428_1423'),
        ('appointments', '0006_auto_20170425_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='treatments',
        ),
        migrations.AddField(
            model_name='appointment',
            name='basket',
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to='users.Basket',
                null=True),
            preserve_default=False,
        ),
    ]
